name: "Binary App ID Generator action"
author: "Ali SN"
description: "Automatically generate App IDs for Binary.com after feature branch has been deployed."
branding:
  icon: "code"
  color: "red"
inputs:
  BINARY_API_TOKEN:
    description: "The Binary token to be used to generate App IDs. Please use a dedicated token. See https://www.binary.com/en/user/security/api_tokenws.html"
    required: true
  BINARY_APP_ID:
    description: "The App ID to be used with Binary API to identify the API connection to Binary."
    required: true
  GITHUB_TOKEN:
    description: "The GitHub token to be used with Octokit to identify the API connection to GitHub."
    required: true
  max_retries:
    description: "Amount of times to retry generating a Binary App ID."
    required: false
    default: 5
  vercel_preview_url:
    description: "The Vercel deployment URL to generate a Binary App ID for."
    required: true
outputs:
  pr_url:
    description: "The URL of the GitHub pull request."
  pr_number:
    description: "The number of the GitHub pull request."
  app_id:
    description: "The newly created or updated Binary App ID."
  should_post_comment:
    description: "Signals the next step whether to post a comment or not."
runs:
  using: "node12"
  main: "dist/index.js"
